### ISSUE TITLE
Creating Wireshark Dissector for CQC Packets

### ISSUE THREAD

**Issue by nalinielkins** [SoftwareQuTech/CQC-Python#18]
Hello,

I have started to build a WireShark dissector using the breakout according to  https://softwarequtech.github.io/SimulaQron/html/CQCInterface.html    We will do an LUA or interpretive dissector until we have the breakouts correct.  

For example, that the original payload in one of the packets is:

020100000000000c0000070500001f537f000001

If you break it out manually, it becomes: 

02 : version: 
01  : type : CQC_TP_COMMAND      
0000 : Application ID,
0000000c : Total length of the CQC packet (excluding this header) : 12

This all makes sense.  But we also get packets starting with 07 and 03 which I am not able to find in the CQCInterface layout above.

Shall I send the entire packet?   Can anyone help?

Thanks,
Nalini Elkins

**Comment by Wojtek242** [comment]
Hi @nalinielkins

It's great to see you're writing a Wireshark dissector! I was going to make one several months ago as I needed one for my own debugging and then realised I don't know LUA so I wrote something simpler just for myself in Rust. Can you send the entire byte stream from the relevant TCP connection and I'll try to see if I can figure out what's going on.

**Comment by nalinielkins** [comment]
Great!  I am attaching the printed packet as well as a PCAP with more packets.  The packets where the payload starts with "02", I can make some progress on.
But where the payload starts with "07" or "03", then I do not know how to break them out.
It would be great to see how you are breaking them out.  Also, if you want to send me some of your pcaps, it will be great.
Maybe we can do a section on your web site with PCAPs and the dissector so that others can have them.
Thanks,

Nalini Elkins
CEO and Founder
Inside Products, Inc.
www.insidethestack.com
(831) 659-8360 

    On Monday, June 10, 2019, 1:18:09 PM PDT, Wojciech Kozlowski <notifications@github.com> wrote:  
 
 
Hi @nalinielkins

It's great to see you're writing a Wireshark dissector! I was going to make one several months ago as I needed one for my own debugging and then realised I don't know LUA so I wrote something simpler just for myself in Rust. Can you send the entire byte stream from the relevant TCP connection and I'll try to see if I can figure out what's going on.

**Comment by Wojtek242** [comment]
I don't think the attachments you sent via e-mail have made it to the GitHub issue page. Would you be able to upload them directly with the issue?

**Comment by AckslD** [comment]
Hi @nalinielkins!

Sorry for my late reply! It's great to see that you're taking action on this :) I'm also not sure why some start with "07" or "03" and would be also be interested in seeing the entire stream.

**Comment by nalinielkins** [comment]
OK.  I am attaching the files.   Sorry for the late reply.  I was travelling.
 
[SimulaQRon.zip](https://github.com/SoftwareQuTech/CQC-Python/files/3296772/SimulaQRon.zip)

**Comment by nalinielkins** [comment]
Axel,
I have attached the files.
Thanks,

Nalini Elkins
CEO and Founder
Inside Products, Inc.
www.insidethestack.com
(831) 659-8360 

    On Tuesday, June 11, 2019, 2:17:59 AM PDT, Axel Dahlberg <notifications@github.com> wrote:  
 
 
Hi @nalinielkins!

Sorry for my late reply! It's great to see that you're taking action on this :) I'm also not sure why some start with "07" or "03" and would be also be interested in seeing the entire stream.

**Comment by AckslD** [comment]
Hi @nalinielkins!

It seems the payload starting with "03" and "07" are actually not part of the communication between the application and the CQC backend, using the CQC interface but rather part of the internal backend simulation (you can see that the port numbers are different, which are set in the [network.json file](https://softwarequtech.github.io/SimulaQron/html/ConfNodes.html#networkconfig)). Note that there are three ports open for each node in the network as visualised in [this figure](https://softwarequtech.github.io/SimulaQron/html/_images/servers.png). So the payloads starting with "03" and "07" are part of twisteds communication between either the CQC server and the SimulaQron server or between the SimulaQron servers.

**Comment by nalinielkins** [comment]
Is there a breakout available for those packets?   Otherwise, many of the packets are not possible to decode.
Thanks,

Nalini Elkins
CEO and Founder
Inside Products, Inc.
www.insidethestack.com
(831) 659-8360 

    On Monday, June 17, 2019, 5:52:43 AM PDT, Axel Dahlberg <notifications@github.com> wrote:  
 
 
Hi @nalinielkins!

It seems the payload starting with "03" and "07" are actually not part of the communication between the application and the CQC backend, using the CQC interface but rather part of the internal backend simulation (you can see that the port numbers are different, which are set in the network.json file). Note that there are three ports open for each node in the network as visualised in this figure. So the payloads starting with "03" and "07" are part of twisteds communication between either the CQC server and the SimulaQron server or between the SimulaQron servers.

**Comment by AckslD** [comment]
@nalinielkins I don't know if a breakout is available for twisted packets, there might be. However, I'm not sure that is very interesting anyway, since that is only used by the simulation backend. In a real implementation of a quantum network the twisted communication wouldn't be there. Maybe an alternative would be to filter out the twisted packets based on the port numbers. What do you think?
