### ISSUE TITLE
network.json file is not coming with pip

### ISSUE THREAD

**Issue by apassenger** [SoftwareQuTech/CQC-Python#19]
Hello,

When I try to install simulaqron with this code lines: (3 times)

pip3 install simulaqron

Simulaqron installed succesfully but when I try to run the code I have this error: No such file or directory /home/name/.local/lib/python3.6/site-packages/simulaqron/config/network.json

So I added network.json manually.

**Comment by AckslD** [comment]
@apassenger For which version of simulaqron do you receive this error?

**Comment by apassenger** [comment]
3.0.4 (I think for starting simulaqron and running code we should restart the machine because after restarting the machine I removed my simulaqron error and When I have this error I didnot restart the machine)

**Comment by AckslD** [comment]
@apassenger Could you set the log-level to DEBUG (10) and include here all the commands you type and the output?

**Comment by AckslD** [comment]
Closing this since there was no reply
