### ISSUE TITLE
quadratic phase gate

### ISSUE THREAD

**Issue by apassenger** [SoftwareQuTech/CQC-Python#23]
Hi,

Is there a quadratic phase gate in cqc ??

**Comment by AckslD** [comment]
What is a quadratic phase gate?

**Comment by apassenger** [comment]
quadratic phase gate P(s)=e(^is(x^2))/2ℏ

**Comment by AckslD** [comment]
What is `s`? What is `x`?

**Comment by apassenger** [comment]
if you can ask me this, cqc is not include  p gate 
thansk
