### ISSUE TITLE
Create Bell PAr

### ISSUE THREAD

**Issue by apassenger** [SoftwareQuTech/CQC-Python#25]
Hi I wrote a fuction but I have this error:

> File "quantum_state_teleportation.py", line 7, in generate_bell_pair
    qubit2 = qubit("Bob")
  File "/home/gozde/.local/lib/python3.6/site-packages/cqc/pythonLib.py", line 1494, in __init__
    if not self._cqc._opened_with_with:
AttributeError: 'str' object has no attribute '_opened_with_with'

How can I remove the error??

 
```
def generate_bell_pair():
 with CQCConnection("Alice") as Alice:
  qubit1 = qubit(Alice)
  qubit2 = qubit("Bob")
  qubit1.H()
  qubit1.cnot(qubit2)
 return qubit1,qubit2
``qubit1, qubit2 = generate_bell_pair()

**Comment by AckslD** [comment]
This should be `qubit2 = qubit(Bob)`
