### ISSUE TITLE
applied Hadamard Gate

### ISSUE THREAD

**Issue by apassenger** [SoftwareQuTech/CQC-Python#27]
As mentioned before too many times, my problem is not related to H gate because I redescribed it so I can use, but in any case I am writing here (but this time you will say the error for me  "you cannot use Hadamard gate with an integer you can use with it qubit"). However my problem is not this!!
When I use  alice_qubits[i].H(), I have the error:

> Traceback (most recent call last):
  File "BB84_.py", line 71, in <module>
    answer.append(BB84(eve = args.eve))
  File "BB84_.py", line 31, in BB84
    alice_qubits[i].H()
AttributeError: 'int' object has no attribute 'H'

```
with CQCConnection("Alice") as Alice:   # And now I connected node for alice
  alice_qubits = []                      # I defined a list for alice
  for bit, base in zip(alice_bits, alice_basis): # And the next 2 lines I crossed the bits and basis and I applied Hadamard gate. You can look this link: 
    alice_qubits.append(base*bit)                # # You can look this link: https://wiki.veriqloud.fr/index.php?title=BB84_Quantum_Key_Distribution#Pseudocode
  for i in alice_qubits:
   alice_qubits[i].H()
   Alice.sendQubit(alice_qubits[i], "Bob")  # My problem is here. After thse steps I want to send the knowled to Bob but I cant send
```

**Comment by AckslD** [comment]
Well that is exactly your problem! If you want to use cqc and simulaqron you need to use the qubit object. You cannot simply create another object, in this case an `int` and expect it to work.

**Comment by apassenger** [comment]
However BB84 protocol is using classic bit and basis firstly like this: https://wiki.veriqloud.fr/index.php?title=BB84_Quantum_Key_Distribution#Pseudocode

**Comment by AckslD** [comment]
CQC is used to communicate with quantum hardware, you don't need quantum hardware to generate a classical bit. Furthermore you cannot apply a hadamard gate to a classical bit

**Comment by apassenger** [comment]
After crossing with basis, then they cab be thought qubit so I can apply a HAdamards gate. Otherwise, of course I cannot apply H gate for a classical bit
