### ISSUE TITLE
Seperating Code as Alice and Bob and... is an Obligatory??

### ISSUE THREAD

**Issue by apassenger** [SoftwareQuTech/CQC-Python#31]
Hi,
Codes were written differently for nodes(What I mean is that each example has at least 2 parts as ALice and Bob and another nodes) Is this an obligatory?? Because we can write codes as a one page??

**Comment by AckslD** [comment]
Technically it is not but it is how it is intended to be. The reason is that this is how you would write actual protocols running on nodes in a quantum network, since they would necessary be running separate processes at the different nodes.
