### ISSUE TITLE
Rotating Angle Doesn't Work

### ISSUE THREAD

**Issue by apassenger** [SoftwareQuTech/CQC-Python#32]
Hi 
I tried this example but "cqc.pythonLib.CQCUnsuppError: Sequence not supported" Why??
Simulaqron also said that: ERROR:VIRTUAL NODE Alice: Cannot apply Cannot apply arbitrary rotation gate in stabilizer formalism - apply_rotation
with CQCConnection("Alice") as Alice:
     q_1 = qubit(Alice)
     q_1.rot_X(round((256/pi)*acos(sqrt(0.9))))

**Comment by AckslD** [comment]
As the error message says "Cannot apply arbitrary rotation gate in stabilizer formalism". To perform rotations you need to use the density matrix formalism (qutip) or the ket formalism (projectq). To change the backend and thus the formalism, see https://softwarequtech.github.io/SimulaQron/html/GettingStarted.html#settings
