### ISSUE TITLE
Toffoli Gate, SWAP Gate and c-SWP Gate

### ISSUE THREAD

**Issue by apassenger** [SoftwareQuTech/CQC-Python#33]
Hi,
For implementing a protocols with Simulaqron-CQC, I need c-SWAP gate.

At least I need Toffoli gate? I could not see Toffoli gate in the documentation. Is there toffoli gate in Simulaqron-CQC? Because it is a standart gate. Even if  c-wap gate is not exist, I should use Toffoli gate

**Comment by AckslD** [comment]
Hi @apassenger !

Three qubit gates are not supported in the current CQC interface. However you can effectively do a Toffoli gate as for example: https://en.wikipedia.org/wiki/Toffoli_gate#/media/File:Qcircuit_ToffolifromCNOT.svg
