### ISSUE TITLE
My code runs forever while using the command CQCConnection.

### ISSUE THREAD

**Issue by ganeshmylavarapu-qp** [SoftwareQuTech/CQC-Python#70]
Hi, 

When I start running the code, with CQCConnection("Alice") as Alice:
the code runs forever and unless I kill it manually it doesn't stop and move to the next step. I am unable to resolve the issue. Please let me know the solution.

Regards,
Ganesh M

**Comment by ganeshmylavarapu-qp** [comment]
![Screen Shot 2020-10-06 at 2 51 34 PM](https://user-images.githubusercontent.com/67536288/95183334-78c3ca80-07e3-11eb-9109-53a31fd2f9ba.png)

**Comment by ganeshmylavarapu-qp** [comment]
Please find the screen shot for reference.

**Comment by AckslD** [comment]
@ganeshmylavarapu-qp, did you start simulaqron (which forms the backed) before? I.e. by doing `simulaqron start` in your terminal? Otherwise the connection has nothing to talk to.

**Comment by ganeshmylavarapu-qp** [comment]
Thank you, I figured it out. Thanks for your reaponse.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
