### ISSUE TITLE
How to use CMD_SWAP command for entanglement swapping.

### ISSUE THREAD

**Issue by ganeshmylavarapu-qp** [SoftwareQuTech/CQC-Python#71]
Hello I created two EPR pairs. One pair (A, B1) and another pair (B2, C). A is in node Alice, B1, B2 in node Bob and C in node Charlie. Now, I want to swap entanglement between B1 and B2. When I try to use SWAP command as mentioned in the arXiv paper swap(B1, B2), it is getting error out mentioning that swap command is not present. Please let me know if there is a way where I can create entanglement between B1 and B2.

**Comment by AckslD** [comment]
Hi @ganeshmylavarapu-qp!

The `SWAP`-command is not supported. You can achieve it by doing:
```python
B1.cnot(B2)
B1.H()
m1 = B1.measure()
m2 = B2.measure()
```
