### ISSUE TITLE
Creating a uni directional network

### ISSUE THREAD

**Issue by ganeshmylavarapu-qp** [SoftwareQuTech/CQC-Python#72]
Hello,

I am trying to create a uni directional network and use repeater system to send a qubit from initial node to final node. I am unable to create unidirectional network while starting in bash mode. Please let me know how can I create a network from bash mode.

Regards,
Ganesh M

**Comment by AckslD** [comment]
Hi @ganeshmylavarapu-qp, what do you mean with bash mode? Did you check this out? https://softwarequtech.github.io/SimulaQron/html/ConfNodes.html#configuring-the-network

**Comment by AckslD** [comment]
Closing this due to lack of reply
