### ISSUE TITLE
Changes in Network.py not working

### ISSUE THREAD

**Issue by ganeshmylavarapu-qp** [SoftwareQuTech/CQC-Python#73]
Hello,

I tried to add new topologies in Network.py program. Whenever I add new topologies, the network is not getting started. I also tried to make changes in the existing topologies and even then the network is not getting started. Please let me know how can I add new topologies and can start them while starting SimulaQron.

**Comment by AckslD** [comment]
Hi @ganeshmylavarapu-qp, could you provide some more details on the code you're trying to run and how you execute it?

**Comment by ganeshmylavarapu-qp** [comment]
Hello,

I am trying to create a unidirectional graph where each node is connected to its successor node. So, I ceated a function in network.py where it takes the count of number of nodes and each node from 0 to n-1 nodes are connected unidirectionally.

But when I added the function in addition to the existing functions like “ring”, “path” and start simulaqron in CLI network is not getting started. The network starts only when the changes are revoked.

Regards,
Ganesh M

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AckslD** [comment]
@ganeshmylavarapu-qp Could you share your code or a small example reproducing this issue?

**Comment by ganeshmylavarapu-qp** [comment]
Please find the modified code. I added a small piece of code for unidirectional graph in network.py program. The code starts at line number 227 and ends at line number 231.

Regards,
Ganesh M

**Comment by AckslD** [comment]
@ganeshmylavarapu-qp Since I think you replied via email, your code is not attached here on github.

**Comment by ganeshmylavarapu-qp** [comment]
Please find the code.
[network.py.zip](https://github.com/SoftwareQuTech/CQC-Python/files/5466902/network.py.zip)

**Comment by AckslD** [comment]
Hi @ganeshmylavarapu-qp, next time it's much easier it you just send the code-snippet in the message itself, especially since it's just a few lines, instead of sending a zip of a python-file.

This is your code correct?
```python
elif topology == "unidirectional":
    if i < nn-1:
        adjacency_dct[node] = [nodes[i + 1]]
```

This will not work since neither `adjacency_dct`, `nn` or `node` is declared before. I think you intended to loop over the nodes, for example as:
```python
elif topology == "unidirectional":
   adjacency_dct = {}
    nn = len(nodes)
    for i, node in enumerate(nodes):
        if i < nn-1:
            adjacency_dct[node] = [nodes[i + 1]]
```
