### ISSUE TITLE
Unable to send classical information using Quantum Repeaters between two nodes.

### ISSUE THREAD

**Issue by ganeshmylavarapu-qp** [SoftwareQuTech/CQC-Python#74]
Hello,

I am trying to implement one of the Gilad Gour papers on Quantum Repeaters. Suppose if Node0, Node1, Node2 are three nodes such Node1 has two qubits one of them is entangled with Node0 and the other is entangled with Node2. For example Node1 has two quits N11 and N12 then, Node0 and N11 are entangled. N12 and Node2 are entangled.

I create an entanglement between N11 and N12. According to the paper since N11 and N12 are entangled, Node0 and Node2 are also in entanglement. Now, I want to teleport a qubit from Node0 to Node2. 

When I write the code the connection is not established between Node0 and Node2 and the code is not complete. Please find the below code and suggest me the issues in my code. I create a path topology between Node0, Node1, Node2.

[Quantum_Repeaters.py.zip](https://github.com/SoftwareQuTech/CQC-Python/files/5440474/Quantum_Repeaters.py.zip)

**Comment by AckslD** [comment]
Hi @ganeshmylavarapu-qp, maybe first take a look at this example: https://github.com/SoftwareQuTech/CQC-Python/tree/master/examples/pythonLib/butterfly

This implements network coding on a butterfly network, following the approach in https://arxiv.org/abs/1710.04827

**Comment by AckslD** [comment]
Closing this due to lack of reply
